/**
 * Lifelink design tokens from Stitch DESIGN.md.
 * Keep NativeWind class names aligned with these values.
 */
export const colors = {
  surface: "#faf8ff",
  "surface-dim": "#d2d9f4",
  "surface-bright": "#faf8ff",
  "surface-container-lowest": "#ffffff",
  "surface-container-low": "#f2f3ff",
  "surface-container": "#eaedff",
  "surface-container-high": "#e2e7ff",
  "surface-container-highest": "#dae2fd",
  "on-surface": "#131b2e",
  "on-surface-variant": "#5b403d",
  "inverse-surface": "#283044",
  "inverse-on-surface": "#eef0ff",
  outline: "#8f6f6c",
  "outline-variant": "#e4beba",
  "surface-tint": "#ba1a20",
  primary: "#af101a",
  "on-primary": "#ffffff",
  "primary-container": "#d32f2f",
  "on-primary-container": "#fff2f0",
  "inverse-primary": "#ffb3ac",
  secondary: "#6e595a",
  "on-secondary": "#ffffff",
  "secondary-container": "#f8dcdc",
  "on-secondary-container": "#745f60",
  tertiary: "#006444",
  "on-tertiary": "#ffffff",
  "tertiary-container": "#008058",
  "on-tertiary-container": "#d3ffe5",
  error: "#ba1a1a",
  "on-error": "#ffffff",
  "error-container": "#ffdad6",
  "on-error-container": "#93000a",
  "primary-fixed": "#ffdad6",
  "primary-fixed-dim": "#ffb3ac",
  "on-primary-fixed": "#410003",
  "on-primary-fixed-variant": "#930010",
  "secondary-fixed": "#f8dcdc",
  "secondary-fixed-dim": "#dbc0c0",
  "on-secondary-fixed": "#261818",
  "on-secondary-fixed-variant": "#554243",
  "tertiary-fixed": "#6ffbbe",
  "tertiary-fixed-dim": "#4edea3",
  "on-tertiary-fixed": "#002113",
  "on-tertiary-fixed-variant": "#005236",
  background: "#faf8ff",
  "on-background": "#131b2e",
  "surface-variant": "#dae2fd",
} as const;

/** Clinical aliases used by some Stitch HTML screens. */
export const brand = {
  red: "#D32F2F",
  redLight: "#FEE2E2",
  redDark: "#991B1B",
  navy: "#0F172A",
  navyLight: "#1E293B",
  slate: "#64748B",
  bgLight: "#F8FAFC",
  success: "#10B981",
  warning: "#F59E0B",
} as const;

export const spacing = {
  "space-2xs": "0.25rem",
  "space-xs": "0.5rem",
  "space-sm": "0.75rem",
  "space-md": "1rem",
  "space-lg": "1.5rem",
  "space-xl": "2rem",
  "space-2xl": "3rem",
  "space-3xl": "4rem",
  "gutter-mobile": "1rem",
  "gutter-desktop": "1.5rem",
  "margin-mobile": "1rem",
  "margin-tablet": "2rem",
  "margin-desktop": "3rem",
  "max-width-content": "80rem",
} as const;

export const fonts = {
  heading: "PlusJakartaSans_700Bold",
  headingSemi: "PlusJakartaSans_600SemiBold",
  display: "PlusJakartaSans_800ExtraBold",
  body: "Inter_400Regular",
  label: "Inter_600SemiBold",
} as const;
