/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        surface: "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "on-surface": "#131b2e",
        "on-surface-variant": "#5b403d",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        outline: "#8f6f6c",
        "outline-variant": "#e4beba",
        "surface-tint": "#ba1a20",
        primary: "#af101a",
        "on-primary": "#ffffff",
        "primary-container": "#d32f2f",
        "on-primary-container": "#fff2f0",
        "inverse-primary": "#ffb3ac",
        secondary: "#6e595a",
        "on-secondary": "#ffffff",
        "secondary-container": "#f8dcdc",
        "on-secondary-container": "#745f60",
        tertiary: "#006444",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#008058",
        "on-tertiary-container": "#d3ffe5",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdad6",
        "primary-fixed-dim": "#ffb3ac",
        "on-primary-fixed": "#410003",
        "on-primary-fixed-variant": "#930010",
        "secondary-fixed": "#f8dcdc",
        "secondary-fixed-dim": "#dbc0c0",
        "on-secondary-fixed": "#261818",
        "on-secondary-fixed-variant": "#554243",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        background: "#faf8ff",
        "on-background": "#131b2e",
        "surface-variant": "#dae2fd",
        brand: {
          red: "#D32F2F",
          redLight: "#FEE2E2",
          redDark: "#991B1B",
        },
        navy: {
          DEFAULT: "#0F172A",
          light: "#1E293B",
        },
        success: "#10B981",
        warning: "#F59E0B",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "1.5rem",
        "margin-mobile": "1rem",
        "margin-tablet": "2rem",
        "margin-desktop": "3rem",
        "max-width-content": "80rem",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        "display-lg": ["PlusJakartaSans_800ExtraBold"],
        "display-sm": ["PlusJakartaSans_700Bold"],
        "headline-lg": ["PlusJakartaSans_700Bold"],
        "headline-lg-mobile": ["PlusJakartaSans_700Bold"],
        "headline-md": ["PlusJakartaSans_600SemiBold"],
        "headline-sm": ["PlusJakartaSans_600SemiBold"],
        "title-md": ["PlusJakartaSans_600SemiBold"],
        "label-blood-group": ["PlusJakartaSans_800ExtraBold"],
        "body-lg": ["Inter_400Regular"],
        "body-md": ["Inter_400Regular"],
        "body-sm": ["Inter_400Regular"],
        "label-lg": ["Inter_600SemiBold"],
        "label-md": ["Inter_600SemiBold"],
        heading: ["PlusJakartaSans_700Bold"],
        sans: ["Inter_400Regular"],
      },
      fontSize: {
        "display-lg": [
          "3.5rem",
          { lineHeight: "4rem", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "display-sm": [
          "2.25rem",
          { lineHeight: "2.75rem", letterSpacing: "-0.015em", fontWeight: "700" },
        ],
        "headline-lg": [
          "2rem",
          { lineHeight: "2.5rem", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "1.5rem",
          { lineHeight: "2rem", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-md": [
          "1.5rem",
          { lineHeight: "2rem", letterSpacing: "-0.005em", fontWeight: "600" },
        ],
        "headline-sm": ["1.25rem", { lineHeight: "1.75rem", fontWeight: "600" }],
        "title-md": ["1.125rem", { lineHeight: "1.5rem", fontWeight: "600" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", fontWeight: "400" }],
        "body-md": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "body-sm": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "label-lg": [
          "0.875rem",
          { lineHeight: "1.25rem", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "label-md": [
          "0.75rem",
          { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "label-blood-group": [
          "1.75rem",
          { lineHeight: "2rem", letterSpacing: "0.02em", fontWeight: "800" },
        ],
      },
    },
  },
  plugins: [],
};
